ALTER TYPE "CmsPageSectionType" ADD VALUE IF NOT EXISTS 'SITE_HEADER';
ALTER TYPE "CmsPageSectionType" ADD VALUE IF NOT EXISTS 'MEDIA_CAROUSEL';
ALTER TYPE "CmsPageSectionType" ADD VALUE IF NOT EXISTS 'SITE_FOOTER';
