ALTER TYPE "CmsPageSectionType" ADD VALUE IF NOT EXISTS 'MEDIA_HERO';
ALTER TYPE "CmsPageSectionType" ADD VALUE IF NOT EXISTS 'MEDIA_GRID_ENHANCED';
ALTER TYPE "CmsPageSectionType" ADD VALUE IF NOT EXISTS 'STORIES_CAROUSEL';
ALTER TYPE "CmsPageSectionType" ADD VALUE IF NOT EXISTS 'VIDEO_SECTION';
ALTER TYPE "CmsPageSectionType" ADD VALUE IF NOT EXISTS 'HIGHLIGHT_CARDS';
