export const LOGIN = 'LOGIN'
export const PASSWORD_CHANGE = 'PASSWORD-CHANGE'
export const DEVICE_SIGN_IN = 'DEVICE-SIGN-IN'
export const PROFILE_UPDATE = 'PROFILE-UPDATE'
export const SECURITY_ALERT = 'SECURITY-ALERT'

export const avatarType = [LOGIN, DEVICE_SIGN_IN, PROFILE_UPDATE]
export const iconType = [PASSWORD_CHANGE, SECURITY_ALERT]
